version: "1.0.0"
services:
  catalog:
    ports:
      - ${CATALOG_PORT}:${CATALOG_PORT}
    build:
      context: .
      dockerfile: Dockerfile.catalog
    env_file: ./.env
  order:
    ports:
      - ${ORDER_PORT}:${ORDER_PORT}
    build:
      context: .
      dockerfile: Dockerfile.order
    env_file: ./.env
  front:
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    build:
      context: .
      dockerfile: Dockerfile.front
    env_file: ./.env
